### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by samthebest** [mucciolo/convexin-tech-test#1]
### Central Crux - Arbitrary Choice of Function Boundaries

Looking at https://github.com/mucciolo/convexin-tech-test/blob/master/src/main/scala/UniqueOddCountValuesByKey.scala

Your function boundaries mix up business logic with IO or parsing/serialisation logic.  The parsing/deserialisation logic, is to deal with the commas and tabs, and turn the strings into integers.  The business logic is to find the numbers occurring an odd number of times.  The problem is best thought with signatures more like this:

```
def read(path: String): RDD[(Int, Int)]
def oddOccurancesByKey(pairs: RDD[(Int, Int)]): RDD[(Int, Int)]
def write(path: String, pairs: RDD[(Int, Int)]): Unit
```

Or a slightly more expanded version:

```
def read(path: String): RDD[String]
def parse(lines: RDD[String]): RDD[(Int, Int)]
def oddOccurancesByKey(pairs: RDD[(Int, Int)]): RDD[(Int, Int)]
def serialise(pairs: RDD[(Int, Int)]): RDD[String]
def write(path: String, lines: RDD[String]): Unit
```

Your methods mix up `parse` and `oddOccurancesByKey` and `serialise`.  There is no clean boundary between dealing with string manipulation and dealing with business logic.

### areAllElementsIntegers

Don't need this, wasn't in the Acceptance Criteria, can just use `toInt`.  We should avoid regex.  Could use Scala native methods, like `isDigit`.

### toKeyValuePair and splitByCommaOrTab

`toKeyValuePair` would be nicer with a pattern match.  You could combine `toKeyValuePair` and `splitByCommaOrTab` into one method, and output integers:

```
def lineToIntPair(line: String): (Int, Int)
```

### Unconvincing Tests

The unit tests, since they need to deal with the mixing up of serialisation and business logic, are difficult to follow.  There isn't really a single unit test that just tests the business logic - of course this is due to the choice of method signatures.

This test is unnecessary complicated:

```
"should return false given an array containing a non-integer" in {
      val numbers = ('0' to '9').toSet
      val nonIntegers = (32 to 126).map(_.toChar).filterNot(numbers).map(_.toString)

      Inspectors.forAll(nonIntegers) { c =>
        areAllElementsIntegers(Array("1", c)) should be (false)
      }
    }
```

Just stick with a few explicit examples, rather than loops.  It seems your solution is _trying_ to find complex solutions where simple solutions would do (like with the use of **partial functions** in the previous version).

This test is the best test:

```
"should return the pairs which the value occurs an odd number of times for the key" in {
      val lines = sc.parallelize(Seq("1,2", "2,3", "1,1", "2,3", "1,2", "2,3", "2,2", "2,2"))
      uniqueOddCountValuesByKey(lines).collect() should be (Array(("2", "3"), ("1", "1")))
    }
```

But would be better if it was in terms of `Int`s not `String`s.  It would be better with a few more examples and variations.

### Advise Extreme Programming - KISS, YAGNI, TDD

All the above can be encapsulated by the concepts of TDD, KISS and YAGNI from XP.  

**TDD:** The above aforementioned test would not have arisen if TDD was being followed - likely one would first see a test with `Nil`, then a test with one element, and so on.  It seems clear that the three laws of TDD have not been followed when this code was written.

**KISS:** Would yield better signatures

**YAGNI:** Would eliminate the unnecessarily complex test, (partial functions), `areAllElementsIntegers`, etc.

**Comment by mucciolo** [comment]
Thank you very much for taking the time to provide such detailed feedback and a opportunity to learn.
